### ISSUE TITLE
Layer groups analysis

### ISSUE THREAD

**Issue by YunxingZuo** [spglib/spglib#103]
I am a big fan of this package and I used it very frequently. Is there any possibility that we can have the "2-dimensional" space group (i.e., layer group) analysis? As far as I understand it, these are merely a subset of 3-d space groups but with only two periodic dimensions. Any response or suggestions toward other readings will be extremely appreciated.

**Comment by atztogo** [comment]
I haven't studied it about layer group. If I understand it correctly, what you wrote is correct. So getting symmetry operations for layer group would be straightforward. What are difficult to provide it from spglib are the symmetry-type assignment and API design. In addition, spglib is written only considering 3d periodicity. So in total, I think it's better to write the code from scratch specific for 2d periodicity. Probably it's much easier to write a code for layer group than space group, because at least primary axis is fixed by user's input.

**Comment by blokhin** [comment]
@YunxingZuo I attach the 2D-3D group mapping table, taken from [Evarestov, 2013](https://doi.org/10.1007/978-3-642-30356-2). In turn, it is based on the International Tables for Crystallography, volume E, Subperiodic Groups, ed. by V. Kopsky, D.B. Litvin (Kluwer Academic, 2002).

We used it in our study of the [SrTiO3 surface phase transition](https://doi.org/10.1103/PhysRevB.88.241407).

![2020-06-04_18-57-37](https://user-images.githubusercontent.com/177388/83788769-fe990300-a695-11ea-8eb5-3509596b81d7.png)

**Comment by YunxingZuo** [comment]
@blokhin Thank you for your comment. I was thinking whether it is possible to implement the slab groups so any interested users can analyze the slab groups just like the excellent work implemented here, especially when @atztogo said it is difficult to provide symmetry-type assignment and API design from spglib. I will take a look at the study and see if I can get some inspiration.

**Comment by atztogo** [comment]
@blokhin , thanks for your information. I wasn't sure about the mapping. Now it's clear. Using spglib for finding layer group is not elegant, because computational resource is wasted for non-necessary symmetry search for the third periodicity. But users can use spglib and this mapping table (or Hall symbol to DG) to determine the layer group. I'm not sure if this mapping should be included in spglib. If we can have a clear definition like the mapping from non-symmorphic to symmorphic, the layer group can be included here,
https://github.com/spglib/spglib/blob/4dd1a92c1a2b81d6905fe245b4cad10bcdaf5c29/src/spglib.h#L139-L151.

**Comment by atztogo** [comment]
It seems no more discussion. I will do nothing for a while on this issue. So I will close this issue now, but please reopen when we want to discuss more.
