### ISSUE TITLE
Missing symmery operations in unconventional unit cell for triangular lattice

### ISSUE THREAD

**Issue by kbarros** [spglib/spglib#131]
Hello, I'm having difficulty finding all symmetry operations for a triangular lattice using an unconventional unit cell. Here is the code with the Python interface

```
import spglib
from math import sqrt

# orthogonal lattice vectors; z component is irrelevant
lattice = [[1, 0, 0],
           [0, sqrt(3), 0],
           [0, 0, 10]]
positions = [[0, 0, 0],
             [0.5, 0.5, 0]]
numbers = [1, 1]
cell = (lattice, positions, numbers)

# Correctly infers spacegroup 'P6/mmm (191)'
spacegroup = spglib.get_spacegroup(cell, symprec=1e-5)

# Something is strange in this dictionary though...
symmetry = spglib.get_symmetry(cell, symprec=1e-5)
```

The code correctly recognizes that both atoms are equivalent: `symmetry['equivalent_atoms']` correctly returns `[0,0]`.

However, if I print `symmetry['rotations']` I find that all matrices are entirely diagonal. None of them "mix" (x,y,z) components. In particular, there is no 6-fold rotation as expected for the triangular lattice. (For reference, I think the elements of this rotation matrix should be `[1/2 3/2; -1/2 1/2]`).

Is this a bug? Otherwise, how should I get symops for the triangular lattice in an orthogonal unit cell? Thanks in advance!

**Comment by atztogo** [comment]
> Is this a bug?

No. Please have a look at issues #126.

**Comment by kbarros** [comment]
Thank you for the pointer, and sorry for not noticing this before. The behavior is clearly documented here:
http://spglib.github.io/spglib/api.html#spg-get-symmetry

It states, _"As an exceptional case, if a supercell (or non-primitive cell) has the basis vectors whose lattice breaks crsytallographic point group, the crystallographic symmetry operations are searched within this broken symmetry,..."_.

I think this resolves the issue.

Questions that might be helpful to answer in the documentation:

- Does there exist a way to get all the symmetry operations for an _unconventional_ cell? (I'm not sure if this question makes sense.)
- Is there a quick way to detect whether the lattice vectors break the crystallographic point group symmetry? (Perhaps this could even be an explicit warning to the caller of `spg_get_symmetry()`?)


Thanks a lot for maintaining this excellent package.

**Comment by atztogo** [comment]
> Does there exist a way to get all the symmetry operations for an unconventional cell? (I'm not sure if this question makes sense.)

I think this is a good question, but you must define your question about 'symmetry operations' more strictly following the crystallography terminology. Otherwise, I may have to think about many corner cases. So in this way, this is what difficult to write its documentation. 

But I guess what you might expect can be achieved by finding a primitive cell, transformation matrix and lattice points inside your unconventional cell. Then getting symmetry operations of the primitive cell (which provides coset representatives of the space group). Thus, you have all information, but you have to apply direct-product of the symmetry operations and lattice translations inside your unconventional cell after transforming the translation (vector) parts of the symmetry operations of the primitive cell to agree with the basis vectors of your unconventional cell. The rule of the transformation is found in the text books of crystallography or https://arxiv.org/abs/1808.01590.

> Is there a quick way to detect whether the lattice vectors break the crystallographic point group symmetry? (Perhaps this could even be an explicit warning to the caller of spg_get_symmetry()?)

You can compare the numbers of unique rotation parts of symmetry operations between the primitive cell and unconventional cell.
How can the warning be emitted the best?

**Comment by kbarros** [comment]
Thank you for the extensive answer and the reference! I am not sure whether a warning would make sense here.

I am learning a lot about space groups as I go, and your spglib has been a huge help for my project. Thanks again.
