### ISSUE TITLE
Get site symmetry information given coordinates and Hall number?

### ISSUE THREAD

**Issue by kbarros** [spglib/spglib#135]
Hello, I was wondering if it is possible to get site symmetry information given fractional coordinates and a Hall number? It would be useful to have Wyckoff position, multiplicity, and the site symmetry symbol.

For reference, one can use Bilbao to look up the Wyckoff positions using this interface: https://www.cryst.ehu.es/cryst/get_wp.html . Maybe Spglib could provide similar information.

Spglib already has a database of site symmetries https://github.com/spglib/spglib/blob/develop/src/sitesym_database.c, so I imagine there already exist routines to look up Wyckoffs, etc., but maybe it is not yet exposed in the public interface?

Thank you.

**Comment by atztogo** [comment]
There is no interface. Spglib is the library to determine crystal symmetry from input structure. But what you expect doesn't need the structure, except for a point coordinate.

There may exist another library for it. Should it be implemented in spglib?

I think it is possible to implement it, but it may not be straightforward. Another difficulty than implementation is that it requires crystallographic knowledge to users. Bilbao Crystallographic Server is very nicely designed to make it easy for users by the web interface.

**Comment by atztogo** [comment]
I will close this issue because no communication for many months. Please reopen when needed.

**Comment by kavanase** [comment]
@kbarros I came across this when searching before for Wyckoff analysis tools, where I wanted to achieve a similar target of determining the Wyckoff label (and point symmetry) of an arbitrary point in a given crystal structure, which may or may not be occupied – in our case, this was in the context of generating and analysing point defects.
I didn't find great tools available for it, but we've now coded in this functionality to our defects code [`doped`](https://doped.readthedocs.io) (submitted to JOSS; https://github.com/openjournals/joss-reviews/issues/6433), in the `get_wyckoff` ([here](https://github.com/SMTG-Bham/doped/blob/a4ea4c8a8a206785cba1f5d9f9db86aee6919b76/doped/utils/symmetry.py#L328C5-L328C16)) and `get_wyckoff_label_and_equiv_coord_list` ([here](https://github.com/SMTG-Bham/doped/blob/main/doped/utils/symmetry.py#L773) functions, which you can see in action in the tutorials / generation code etc.

Implements two different approaches, one where it uses `spglib` to determine and populate all the equivalent sites (so that the overall space group / periodicity isn't broken) and then uses `spglib`'s symmetry tools with this structure, or an alternative where it essentially uses algebra with lookup tables to determine the Wyckoff label (according to the BCS convention). Thought I'd share in case it's useful!
