### ISSUE TITLE
Axis choices within a Hall symbol for orthorhombic space groups

### ISSUE THREAD

**Issue by lan496** [spglib/spglib#220]
As @atztogo clarified (https://github.com/spglib/spglib/pull/209#issuecomment-1371798671), `spacegroup.c:num_axis_choices_ortho` gives the number of axis choices with preserving a Hall symbol. This number is used to "sort" three axes.

https://github.com/spglib/spglib/blob/dbc88b84d6827bfed0c4d4e1b85b29fdc126f915/src/spacegroup.c#L231-L251

I have also confirmed `spacegroup.c:num_axis_choices_ortho` with the list of Hall symbols for orthorhombic space groups. Here is my understanding of the conventions for axis choices. Let `num_free_axes = num_axis_choices_ortho[spacegroup_type.number - 16]`. `num_free_axes` determines how to permute axes of the orthorhombic space group.

(Updated: initial wrong description for `num_free_axes==1` and `num_free_axes==6` are corrected.)
- `num_free_axes==1`: The axis choices give six Hall symbols. No freedom to permute axes.
- `num_free_axes==2`: The axis choices give three Hall symbols. Each pair of axis choices {abc, ba-c}, {cab, -cba}, and {bca, a-cb} gives the same space groups, respectively. Spglib imposes a'<b' in the new coordinate systems.
- `num_free_axes==3`: The axis choices give two Hall symbols. Each triplet of axis choices {abc, bca, cab} and {ba-c, a-cb, -cba} give the same space groups, respectively. Spglib imposes a'<b' and a'<c'.
- `num_free_axes==6`: All axis choices give the same Hall symbol. Spglib imposes a' < b' < c'.

If I understand correctly, `num_free_axes = 6 / (number of unique axis choices)`. For example, Pban (No. 50) has three Hall symbols: 50:1, 50:2, 50:1cab, 50:2cab, 50:1bca, and 50:2bca. Then, `num_free_axes = 6 / 3 = 2`.

If this behavior is expected, the index of Affine normalizers (currently used) does not necessarily give the number of unique axis choices. For example, the index of Imma (No. 74) is two, "x,y,z" and "y+1/4,x-1/4,z+1/4". However, because "y,x,-z" does not belong to the Affine normalizer, axis choice ba-c gives a different Hall symbol.

Thus, I think the index in `spacegroup.c:num_axis_choices_ortho` for the following two orthorhombic space groups should be corrected:
- Ibca (No. 73): Current 6 -> Proposed 3
  -  Two unique axis choices in ITB
- Imma (No. 74): Current 2 -> Proposed 1
  - Six unique axis choices in ITB

@atztogo Does it make sense? Also, why Cmma (67), Ccca(68), Ibca(73), and Imma(74) are specially treated, https://github.com/giovannipizzi/seekpath/issues/57#issuecomment-507035290 ?

Note: ITB gives different Hall symbols for identical space groups for the following two orthorhombic space groups:
- Cmme (No. 67): Six distinct axis choices in ITB, but actually some of them are identical (e.g. 68:1 and 68:1ba-c). In fact, the previous ITA in the fifth edition labeled it as Cmma.
- Ccce (No. 68): Same as Cmme. Previously Ccca.

**Comment by site-g** [comment]
>- `num_free_axes==2`: three sets of axis choices {abc, ba-c}, {cab, -cba}, and {bca, a-cb} give the identical space groups, respectively. Spglib imposes a'<b' in the new coordinate systems.
>- `num_free_axes==3`: two sets of axis choices {abc, bca, cab} and {ba-c, a-cb, -cba} give the identical space groups, respectively. Spglib imposes a'<b' and a'<c'.
>- `num_free_axes==6`: each axis choice gives a different space group. Spglib imposes a' < b' < c'.

I am a little confused about the _identical space groups_ and _different space group_ in your description. For _identical space groups_, do you mean identical hall symbol? Besides, take the simplest case P 2 2 2 (16) as an example. It has `num_free_axes==6`. Swapping abc neither changes space group nor hall symbol, but you said

> each axis choice gives a different space group.

**Comment by lan496** [comment]
@site-g Thank you for your comment! The descriptions for `num_free_axis==1` and `num_free_axis==6` should be swapped (I was confused even in writing). I've updated the descriptions.

For "identical space groups", I mean equivalent as a set of matrices (and the identical Hall symbol).

**Comment by site-g** [comment]
If I understand correctly, the terminology "space group" used here is equivalent to "Hall symbol"? Then "each axis choice gives a different space group" and "all axis choices give different Hall symbols" are talking about the same thing. Swapping them might not make any sense.

Still considering P 2 2 2 (16), the hall symbol keeps to be P 2 2 no matter the axis is abc, ba-c, cab or any other. `num_free_axes==6` might be: all axis choices give same Hall symbols?

**Comment by lan496** [comment]
> the terminology "space group" used here is equivalent to "Hall symbol"?

Yes, you are completely right. I've fixed `num_free_axes==6` in the above comment. Sorry for my sloppy explanation...

**Comment by site-g** [comment]
@lan496 If I'm not mistaken, your modifications are

- Cmme (No. 67): 2 -> 2
- Ccce (No. 68): 2 -> 2
- Ibca (No. 73): 6 -> 3
- Imma (No. 74): 2 -> 1

I skimmed reference article of [SeeK-path](https://doi.org/10.1016/j.commatsci.2016.10.015) and found your result coincides with theirs in section 3.1.3, i.e. following Table 2.2.6.1 of ITA (5th edition) or Table 2.1.3.4 in 6th edition. `Number of distinct projections` in that table is what you called `number of unique axis choices`. Appendix A in the article explains very briefly why Ibca (No. 73) and Imma (No. 74) are special and why they don't use Euclidean normalizer. However, the article was published in 2017 and issue [seekpath#57](https://github.com/giovannipizzi/seekpath/issues/57) appeared in 2019. Then @atztogo  switched the reference to Euclidean normalizer. If you modify it back, the problem will arise again.

There are in fact two different problems. One of them is some Hall symbols in ITB are redundant, as you have pointed out. This affects Cmme (No. 67) and Ccce (No. 68) and choices in Table 2.2.6.1 of ITA is correct. The other is for Ibca (No. 73) and Imma (No. 74), m · n ≠ 6 as mentioned in Appendix A of the SeeK-path article, where m comes from Euclidean normalizer, n is `number of unique axis choices`. I think the problem comes from n, i.e. some of the unique axis choices is in fact not unique. Take Imma (No. 74) as an example, switch axis choice abc to ba-c would change Imma to Immb. However, as you can see from the [symmetry diagram](https://onlinelibrary.wiley.com/iucr/itc/Ac/ch2o3v0001/sgtable2o3o074/), Imma in fact also has a **b** glide plane which is 1/4**c** above its **a** glide plane. We do not call it Imme just because the two planes are not at same height. Rather than swapping the axes, shift origin to (1/4, 1/4, 1/4) can also change Imma to Immb. If you agree that Cmma and Cmmb have same axis choice, then Imma is in same situation.

This is just my conjecture, I cannot prove it. The setting choices involve personal judgements while Euclidean normalizer comes from mathematical calculations so I believe it more.

**Comment by lan496** [comment]
> Cmme (No. 67): 2 -> 2
> Ccce (No. 68): 2 -> 2
> Ibca (No. 73): 6 -> 3
> Imma (No. 74): 2 -> 1

Yes, that's my conjecture.

> some Hall symbols in ITB are redundant, as you have pointed out.
> This affects Cmme (No. 67) and Ccce (No. 68) and choices in Table 2.2.6.1 of ITA is correct.

Seekpath paper says "The ‘‘number of distinct projections” is the same as the number of different symbols for the space group number in Table A1.4.2.7 of the ITB [19]" (Ch. 3.1.3), but that was not correct for Cmme (No. 67) and Ccce(No. 68).
So, the current spglib's behavior for the two orthorhombic space groups has been fixed correctly.

> If you modify it back, the problem will arise again.

> I think the problem comes from n, i.e. some of the unique axis choices is in fact not unique.

> If you agree that Cmma and Cmmb have same axis choice, then Imma is in same situation.

Totally agree.
Actually, I have not read Ch 2.1 of ITA 6th ed. and Seekpath paper thoroughly.
I will read them more seriously and think about how to formally define choices of basis vectors.

**Comment by lan496** [comment]
@site-g I have understood that the current normalizer-based approach is more sound than the (previous) seekpath approach, thanks to your comment.

The ITA (6th ed.) defines projections are "distinct" if they have different Hermann-Mauguin symbols. This definition is actually not the finest classification: as you have pointed out, heights of glide planes are missed for example.

The finer definition for distinct projections will be based on Hall symbols, which the current spglib adopts. This finer definition will be more appropriate for our usage.
