### ISSUE TITLE
Version consistency check between CMakeLists.txt and pyproject.toml, e.g. by pre-commit?

### ISSUE THREAD

**Issue by atztogo** [spglib/spglib#231]
In the meantime, we will write the same version number manually in two files (#228). I am almost sure that I will forget this. So I would need a mechanism to remind it to me.

**Comment by LecrisUT** [comment]
I have a method to automatically set the `CMakeLists.txt` version according to git tags. Recently `scikit-build-core` also implemented `setuptools_scm` so we can unify the version like that. Should we implement that? Here's [an example](https://github.com/LecrisUT/CmakeExtraUtils/blob/180604da50a3c3588f9d04e4ebc6abb4e5a0d234/cmake/DynamicVersion.md) of the interface.

Maybe the only question is, if we want this is, do we add that project as an external dependency that is downloaded/retrieved from system, or do we embed the code here? With the former, it will be easier for me to maintain and fix the issues related to that code (Note that [`PackageCompsHelper.cmake`](https://github.com/spglib/spglib/blob/develop/cmake/PackageCompsHelper.cmake) is also migrated there), but the naming of that project might change because I do not have enough creativity to come up with names.
