### ISSUE TITLE
Clen up repo

### ISSUE THREAD

**Issue by LecrisUT** [spglib/spglib#244]
We've got quite a lot of unused files like `.travis.yaml`. Most of them are straightforward to delete. The only one that needs discussing is the ruby api. For that it would be more beneficial to switch to swig to automatically generate and keep up to date the api bindings. This would make the project have a soft dependency on swig though.

**Comment by atztogo** [comment]
When I started developing spglib (more than 10 years ago), I was rather a ruby user than python. At that time, use of C-API of ruby was a better idea for me. Now I forget almost everything about ruby, and have no ability to maintain the ruby interface. Probably we have to look for a maintainer of the ruby interface, otherwise I think we can drop the ruby support.
