### ISSUE TITLE
Bump numpy version

### ISSUE THREAD

**Issue by LecrisUT** [spglib/spglib#407]
Looks like numpy 2.0 is just around the corner: https://github.com/numpy/numpy/issues/24300. But in the meantime we should still update the numpy version currently used, since we are still using `1.7` deprecated api:
- Remove the `#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION` and fix the api
- Numpy has minimum version of `3.9`, maybe we should bump it as well, although `pip install` should pick up the appropriate version automatically

**Comment by atztogo** [comment]
Should we wait for EOL of python 3.8?

**Comment by LecrisUT** [comment]
I think we can support both of them. We have `3.8` in the CI, so we are able to pick up the maximum numpy version compatible with python 3.8

**Comment by LecrisUT** [comment]
This one seems quite more complicated [^1], might be better to deffer to numpy 2.0 and find a guide on migration.

[^1]: https://github.com/numpy/numpy/issues/24855

**Comment by jakirkham** [comment]
Hi All 👋

NumPy is planning to release 2.0 on June 16th ( https://github.com/numpy/numpy/issues/24300#issuecomment-2125643448 ). NumPy 2.0.0 RC packages for conda & wheels came out at the beginning of April ( https://github.com/numpy/numpy/issues/24300#issuecomment-2030603395 ) 

NumPy has put out [a migration guide]( https://numpy.org/devdocs/numpy_2_0_migration_guide.html#numpy-2-migration-guide ). More details are in [the release notes]( https://numpy.org/devdocs/release/2.0.0-notes.html )

If Spglib makes use of NumPy's C API (and produces wheels that use it), having a release of Spglib with wheels built against NumPy 2.0.0rc1 would be helpful to ensure NumPy 1 & 2 compatible wheels (as wheels built against NumPy 1 won't be compatible with NumPy 2). More details in [this NumPy 2 ABI doc]( https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-abi-handling )

Also as NumPy is tracking ecosystem support for NumPy 2.0, it would be helpful to share Spglib current support status in issue (with any plans): https://github.com/numpy/numpy/issues/26191

**Comment by LecrisUT** [comment]
Sorry I didn't get back to this. I think we should make the numpy version be either python version dependent or fully only support numpy 2.0 and later. @atztogo @lan496 any preference?

**Comment by atztogo** [comment]
@LecrisUT, I have no preference.

**Comment by jakirkham** [comment]
It should be possible to build with NumPy 2 and create binaries that run with NumPy 1 & 2 for Python 3.9+

Please let us know if you have any questions about this 🙂

Edit: For Python 3.8, one can continue to use [`oldest-supported-numpy`]( https://pypi.org/project/oldest-supported-numpy/ ). There is no NumPy 2 for Python 3.8. So the `oldest-supported-numpy` logic still works there

**Comment by LecrisUT** [comment]
> It should be possible to build with NumPy 2 and create binaries that run with NumPy 1 & 2 for Python 3.9+

Can you elaborate on this? I had the impression that the soversion changed for the numpy library. What exactly changed for numpy 2.0 that requires wheel rebuilds?

**Comment by rgommers** [comment]
The NumPy ABI changed (lots of individual changes, and removal of some deprecated/duplicate C API functions/objects), so you cannot build with 1.x and use 2.x at runtime. The reverse is possible though, because NumPy added a compatibility shim to make that possible. So building with 2.x is compatible with all possible 1.x versions as well as with 2.x (xref [the numpy docs on this topic](https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-0-specific-advice)).

soversion isn't quite relevant, since there is no direct dependency between shared libraries (your own extension modules won't contain a `DT_NEEDED` for `some_numpy_sharedlib.so`).

You currently have the following in `pyproject.toml`:
```toml
[build-system]
requires = ["scikit-build-core", "numpy"]
```
That's already a footgun, which will be wrong in several cases. You want the following if you support Python >=3.9:
```toml
requires = ["scikit-build-core", "numpy>=2.0.0"]
```
and if you want to keep Python 3.8 support you want:
```toml
requires = [
    "scikit-build-core",
    "numpy>=2.0.0; python_version>='3.9'",
    "numpy>=1.25.0,<2.0; python_version<'3.9'",
]
```

EDIT: your runtime dependency is fine, it can be lower than the build-time dependency as long as you build with numpy>=1.25.0

**Comment by rgommers** [comment]
> Remove the `#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION` and fix the api

Please don't remove the define completely. The define means "don't use NumPy C API objects that were deprecated before 1.7". You can either leave it alone, or change it to:
```C
/* set this to the lowest support numpy version */
`#define NPY_NO_DEPRECATED_API NPY_1_20_API_VERSION` 
```

**Comment by lan496** [comment]
@LecrisUT I have no preference too.

**Comment by LecrisUT** [comment]
@rgommers @jakirkham, mind if I tag you guys on a PR to review and discuss some designs?

Right now I plan to:
- bump `NPY_NO_DEPRECATED_API`, just because
- figure out the `build-system.requires`, I do not wish to add a lower-bound to `numpy` because that can make it unbuildable on distro packages
- general review to keep the python bindings up to date

**Comment by rgommers** [comment]
No problem, please feel free to Cc me.

> figure out the `build-system.requires`, I do not wish to add a lower-bound to `numpy` because that can make it unbuildable on distro packages

Distros won't have a problem with this, they're very much used to this and they do not use `pyproject.toml` but their own metadata file. Many projects, including all the most popular ones like Pandas/Matplotlib/SciPy/scikit-learn do it like I suggested, because it's the only decent option. I've gotten into the habit of annotating the metadata to avoid confusion from distro packagers on this, e.g.: 

https://github.com/scipy/scipy/blob/342df6964fd91179132c2ccedb1a4f1a8b9fa963/pyproject.toml#L25-L31

**Comment by LecrisUT** [comment]
@atztogo @lan496 While investigating #496 I am inclined to migrate to pybind11 or nanobind. Doing the bindings manually, while not *too* difficult, we are missing some boilerplate that could have been handled behind the scenes by those libraries, e.g. checking numpy ABI compatibility, or error handling `PyModule_Create`. What do you think of such migration?

**Comment by atztogo** [comment]
@LecrisUT, I would like to follow your idea.

**Comment by lan496** [comment]
@LecrisUT I agree with migrating pybind11 or nanobind too. I've used pybind11 in my projects and like it, although I haven't used nanobind.
