### ISSUE TITLE
spglib_f08.F90 seems broken in v2.3.0

### ISSUE THREAD

**Issue by dmt4** [spglib/spglib#415]
Hello,

spglib_f08.F90 from v2.3.0 now has 'use spglib_version' but spglib_version.mod is not included in the installation, nor spglib_version.f90. However I see spglib_version.f90 and its corresponding .mod are being generated as part of the build.

Beyond this, I'm not sure what is the benefit of having the version in a module in its own right. Simply having the version info placed in spglib_f08.F90 is much less hassle to use.

Best wishes,
Dimitar

**Comment by LecrisUT** [comment]
Separating that is for #397 where you will be able to build the Fortran interface on a pre-installed spglib library. This is relevant because Fortran modules are ABI incompatible between compilers, while the C library is much more compatible.

Hmm, I think I made a mistake when writing that and the `spglib_f08.F90` should not have a `use spglib_version` on the module level, but on the submodule one so that you don't need to package the `spglib_version.mod` file.

Can you help me test this? I'll make a quick patch shortly

**Comment by LecrisUT** [comment]
Wait, the tests are passing on `testing-farm` which does not have access to `spglib_version.mod`. @dmt4 what errors exactly do you find when consuming the `spglib_f08.mod`? Is the issue with consuming `spglib_f08.F90` instead? If it's the latter, how do you do it?

**Comment by dmt4** [comment]
What you described is pretty much what I do: generate a module from the .F90 file locally as part of my build so as to reuse a single binary distribution of the lib for different fortran compilers (I think I may have asked the original author back then to also install the .F90 file and not just the .mod).

The issue is that spglib_f08.F90 has that statement 'use spglib_version' but none of either spglib_version.f90 or spglib_version.mod is installed to the prefix/cmake_install_prefix location. Maybe your test only uses spglib_f08.mod only? In that case the data from spglib_version is already bundled in it so it works.

I was thinking, since spglib_version.f90 is generated dynamically from a template could you instead put the version data straight in spglib_f08.F90? This way it seems it will work as before but with version data available.

**Comment by LecrisUT** [comment]
In that case I think we need to install `spglib_version.f90` and not `spglib_version.mod`

> Maybe your test only uses spglib_f08.mod only?

The tests are done with the same compiler so it will be using the `spglib_f08.mod` and that one seems to work without bundling its module dependencies. We are testing the versions, so we are importing the contents that would have been in `spglib_version`.

But what I am more curious is how do you consume it to try the `.mod` file first and if it's incompatible recompile the `.F90` files. CMake does not seem to support it, but it would be great if we could just include this in the `SpglibConfig.cmake` to automatically do this. My only guess would be using `include`, but then how would it pick up the mod file?

Or rather more basic question, are you using it within a CMake environment?

**Comment by dmt4** [comment]
Not using it from cmake. I just compile the f90 inplace during application build and never bother checking the installed .mod. The issue with mod is that there is not even guarantee that it is compatible across diff versions from the same compiler so in my view it is not worth dealing with it as distributable.

Back to cmake, I'd imagine it is possible somehow to do this there but I haven't looked recently.
It seems the trend there is to build whole packages as private dependencies rendering all these fine arguments about f90/mod moot.

**Comment by LecrisUT** [comment]
> The issue with mod is that there is not even guarantee that it is compatible across diff versions from the same compiler so in my view it is not worth dealing with it as distributable.

Indeed, but it is still important to make the preference for `.mod` files whenever compatible for downstream packaging, lua-module environments etc. Also the `.mod` will have all of the release and upstream compile flags set, while the `.F90` will always use the downstream compile flags.

Ok, here is my plan:
- I will add the generated `spglib_version.f90` into the `/include` path. This is not ideal because `/include` should have minimal number of project specific files inside, but I think making a `/include/spglib` would be even worse at this point unless we move all include there.
- I will try to implement #416 and test locally if this works
- For non-cmake consumers, they should have a way to grep all `spglib_*.f90` files and include them as their own sources and ignoring the packaged `.mod` file

@dmt4 you might have had experience with this as you have been consuming the f90 files. Does Fortran prefer the build directory's `.mod` file, or at least try all `.mod` files with the same name but different paths?

**Comment by dmt4** [comment]
Don't remember if fortran (the published std) deals with this, it may be down to the compiler, that said usually the same directory as the source file is looked up then other supplied or intrinsic search directories.

I think just adding spglib_version.f90 to the include is just too much trouble, because now will have to compile it then compile spglib_f08.. all that just for a couple numbers specifying the version. What is the issue with just putting the version data inside spglib_f08.F90 and not having a separate spglib_version.f90?

About the precompiled mods, does lua use them in any way? I didn't know. The issue goes beyond just the mod file, if there is any data there also .o file which ends up forming libspglib_f08.so in this case, this is now also compiler specific (although more compatible than the mod itself) so it is also not generally useful, with this also go whatever gfortran flags were used for it. Binary portability does not seem to have figured as any concern for the language committee. In high performance computing where fortran tends to be used usually multiple versions of a packages are build with various compilers and one simply chooses the one to use for particular setup to keep things consistent.

The only use case where i see .mod and libspglib_f08.so being useful if when hacking about on something tiny with the native compiler and without any build system. I guess for this alone is worth having them.

Anyway the pointed I wanted to emphasise is, it will be easiest to just merge the contents of spglib_version.f90 into spglib_f08.F90 and eliminate spglib_version.f90. The use of the module file spglib_f08.mod will be unaffected by this.

**Comment by LecrisUT** [comment]
> What is the issue with just putting the version data inside spglib_f08.F90 and not having a separate spglib_version.f90?

It breaks tooling such as `fpretiffy`. That's why I try to minimize the generated headers like that. What I could do instead is to concatenate the built file `spglib_f08.F90` and export the concatenated version. Would that also work?

> About the precompiled mods, does lua use them in any way? I didn't know.

Sorry I was referring to `lmod` a.k.a. `module load`. What I meant by that is environments that have more specific build conditions such as on HPC. In those cases the toolchain is homogeneous so `.mod` files are guaranteed to be compatible.

**Comment by dmt4** [comment]
Ok, I think the version module would have to be the first in the concatenation, otherwise it will likely not compile. Seems like a tail wagging the dog situation with fpretiffy but is fine if you like it and it works.

I see what you mean with lmod, another useful case is the aforementioned private dependency builds.

**Comment by LecrisUT** [comment]
Btw, I should also mention the changes in #397. There you can build the fortran bindings as standalone like:
```cmake
FetchContent_Declare(Spglib_fortran
		GIT_REPOSITORY httsp://github.com/spglib/spglib
		GIT_TAG develop
		SOURCE_SUBDIR fortran
)
FetchContent_MakeAvailable(Spglib_fortran)
```

**Comment by dmt4** [comment]
Thanks, but if one goes this far I think is only a tiny extra step to just build the whole lot in the same way and forget about trying to reuse any preexisting lib.

**Comment by LecrisUT** [comment]
Indeed, it just offers more ways that users and packagers can consume the project. My main focus for this issue are to combine the packaged f90 files and #416, after that we should release a 2.3.1 bug fix release
