### ISSUE TITLE
Can the primitive cell obtained by spglib always ensure the elastic tensor has the standard form?

### ISSUE THREAD

**Issue by hongyi-zhao** [spglib/spglib#464]
[Vaspkit](https://vaspkit.com/), which uses spglib to do the primitive cell conversion in its low-level, can ensure the computed elastic tensor has the standard form, say, as described [here](https://mp.weixin.qq.com/s?__biz=MzI2OTQ4OTExOA==&mid=2247485044&idx=2&sn=80178d0bda6de43e3a5e4a47a72aa158&chksm=eadec0c5dda949d31853dafa37ae593b96f872990bf7b7ada0cbb89bf5e64bbc66903d8794e4&scene=21#wechat_redirect), for the cubic system, the form is as follows:

![image](https://github.com/spglib/spglib/assets/11155854/7549ea15-40bf-449f-8d6e-bcad085d96fe)

![image](https://github.com/spglib/spglib/assets/11155854/da78fe9b-a444-47ea-b89c-c5bc83b4de63)

So, I am interested in the following questions: 

1. If [the primitive cell obtained by spglib](https://spglib.readthedocs.io/en/latest/definition.html#transformation-to-the-primitive-cell) always ensures the elastic tensor has the standard form?
2. If a base transformation is performed, how should the corresponding tensor change?
3. If I want to convert the tensor of a system to the standard form, what kind of base transformation should I do?

See [here](https://www.vasp.at/forum/viewtopic.php?p=26055#p26055), [here](https://github.com/materialsproject/pymatgen/issues/3720), and [here](https://github.com/SMTG-Bham/easyunfold/issues/48) for the related discussions.

Regards,
Zhao

**Comment by atztogo** [comment]
@hongyi-zhao, I don't know, because I don't know the way how Vaspkit uses spglib, and I don't see your definiton of 'starndard form'. Therefore the following is just my guess.

If Vaspkit standardizes your crystal structure using https://spglib.readthedocs.io/en/stable/api/python-api/spglib/spglib.html#spglib.standardize_cell with `no_idealize=False`, the basis vectors are set on one of nice orientations for the corresponding Bravais lattice, I think it results in your standard form.

I am afraid of answering more because those would be answered by the standard text book Physical Properties of Crystals by J. F. Nye.
