### ISSUE TITLE
Installing both static and dynamic link library under cmake

### ISSUE THREAD

**Issue by atztogo** [spglib/spglib#465]
Currently, conda forge package of spglib installs only dynamic link library. Previously the static link library was provided. Can we install both of the dynamic and static link library under the current system of cmake?

**Comment by LecrisUT** [comment]
Yes, I've added this functionality explicitly. See [homebrew recipe](https://github.com/Homebrew/homebrew-core/blob/571b687a04df5984aa81ba8d92c34fbfd9800a0b/Formula/s/spglib.rb#L27-L35), basically you just run cmake configure-build-install twice with `SPGLIB_SHARED_LIBS=ON/OFF`.

I did not implement this feature in conda because I am not sure about their packaging policy, e.g. with Fedora you mustn't make static libraries unless there is a very good reason. The issue is generally that the distro packaging systems must make sure that when they update a package `foo`, all the dependent packages `bar` pick up the appropriate dependecy and are tested against that.

`homebrew` packaging seems to be shifting towards vendor packaging instead (more like flatpak, snap, etc.), where each package bundles most dependencies, and the users are expected to only install and manage leaf applications. In this case adding both versions is more expected for the end-user.

Unfortunately conda uses a distro packaging model rather than vendor model

**Comment by atztogo** [comment]
Thanks for your reply, @LecrisUT. I see your point about the package chain in conda forge. I don't have a very good reason, but I personally like static link libraries in compiling scientific software that we have to build from source code manually. I consider a situation that spglib static link library is installed via conda, and some other software(1) is distributed only by source code. Of course, it is possible to use dynamic link library for the case, but when telling other people how to build the software(1), it is often easier to avoid troubles, especially the software(1) is under the chaotic development.

**Comment by LecrisUT** [comment]
A few things need to be clarified:
- who is the target audience that would use the static library
- what issues do static linkage prevent that are in shared libs
- how is the user using the static library, from build step up to install and run step, and what is their environment like

Depending on all of these there could be other recommended solutions:
- embed spglib dependecy as `FetchContent` without `find_package`. That is more guaranteed that the version is stable
- use other packaging systems like spack where you have better control of the dependency versions
- build spglib manually on the local system

It is also worth considering:
- conda is a packaging system built for python projects, not for compiled projects
- static linkage of spglib does not mean libm and python linkage is also static. This can have disastrous consequences when upgrading the linked libm/libpython either from conda or on the system
- if the issue is about python bindings and how it detects the spglib library than it is better discussed in #462

**Comment by atztogo** [comment]
Thanks @LecrisUT your comments and advices!

>who is the target audience that would use the static library
>what issues do static linkage prevent that are in shared libs
>how is the user using the static library, from build step up to install and run step, and what is their environment like

My colleague develops his code for which he uses spglib library. Since we install spglib via conda-forge, we get the C library, he could use it when compiling his C++ source code.
To use shared libraries, we have to property specify LD_LIBRARY_PATH or something like that. Using static link library, it is not necessary.

>embed spglib dependecy as FetchContent without find_package. That is more guaranteed that the version is stable
>use other packaging systems like spack where you have better control of the dependency versions

People think lifetime of their scientific code is short enough and learning packaging stuff does not justify the investment.

>build spglib manually on the local system

This is very possible solution, but simply conda-package was convenient.

>conda is a packaging system built for python projects, not for compiled projects

I use conda-forge as an isolated evnironment to compile and execute various scientific codes, and it works very well. It is also easy to write documentation of how to install such code, e.g., https://phonopy.github.io/phono3py/install.html#installation-instruction-of-latest-development-version-of-phono3py.

>static linkage of spglib does not mean libm and python linkage is also static. This can have disastrous consequences when upgrading the linked libm/libpython either from conda or on the system
>if the issue is about python bindings and how it detects the spglib library than it is better discussed in https://github.com/spglib/spglib/issues/462

I didn't consider this situation.

**Comment by LecrisUT** [comment]
> To use shared libraries, we have to property specify LD_LIBRARY_PATH or something like that.

I recommend not building manually. CMake adds appropriate `RPATH` for the build directory if you want to quickly prototype something, and for more production-like environments, you can use [`CMAKE_INSTALL_RPATH_USE_LINK_PATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_RPATH_USE_LINK_PATH.html) which will populate it after a `cmake --install` as well.

> People think lifetime of their scientific code is short enough and learning packaging stuff does not justify the investment.

But that's why I recommend a `FetchContent` like setup, not for packaging, but because it makes adding dependencies a trivial task. I have noticed we lost the `FetchContent` example, but here is a minimal starting point that I would recommend

<details><summary>Example project</summary>

```cmake
cmake_minimum_required(VERSION 3.20...3.29)
project(example_spglib LANGUAGES C)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)

include(FetchContent)
FetchContent_Declare(Spglib
        GIT_REPOSITORY https://github.com/spglib/spglib
        GIT_TAG v2.3.0
)
FetchContent_MakeAvailable(Spglib)

add_executable(example example.c)
target_link_libraries(example PRIVATE Spglib::symspg)
```

</details>

CMake interface is not as bad as people claim it is, especially if you use modern CMake standards. IDEs (CLion or VSCode, not emacs or vi) help you a lot in getting started from the first hello-world files, to running and debugging your application. I recommend new people to learn this, because it is much easier than the alternative of learning linking libraries, compiler cli, `LD_LIBRARY_PATH`/`RPATH`, etc. People often believe it is the opposite, but that is because they have spent a lot of time learning all of these manual interface and find them trivial knowledge now.

> I use conda-forge as an isolated environment to compile and execute various scientific codes, and it works very well

Indeed, but there are various nuances that are only encountered further down the line when you dig deeper, e.g.:
- conda distributes pre-built libraries, what if the dependencies (e.g. `libm`) do not match the build environment
- where does conda draw the line in system vs conda packages
- compiler consistency

Overall `spack` has better control over these, but I do not recommend new people to start with that. Instead I recommend 2 workflows:
- `C` api: use CMake with the starter example above
- `Python` api: Create a python virtual environment `python3 -m venv name_of_venv`, source it and just run `pip install spglib`. Most things are handled by `pip` or `scikit-build-core`, including building from `sdist` (a.k.a. build from source) directly if there is no compatible package

**Comment by atztogo** [comment]
Thanks @LecrisUT. The original idea was using static link library provided from conda-package. So I didn't consider to make it from source code. I will close this issue.

Apart from spglib package, I don't expect very best to conda-forge package, but it often works very well. Since the compiler is also provided, it helps saving my time to struggle on preparing building environment, especially for telling how to install a code to other people. For example, building phono3py does not become so simple if I don't rely on conda-forge's multithreaded BLAS or openmp library along with the provided compiler.

**Comment by LecrisUT** [comment]
> For example, building phono3py does not become so simple if I don't rely on conda-forge's multithreaded BLAS or openmp library along with the provided compiler.

You know I can help and make that build system become simpler on that end, similar to over here right? It would probably take 3 PRs: setup a similar CI infrastructure, build up the CMake project, setup other project organizations. With how sglib is now setup, I can make it that it easily installed both from `pip` and `cmake` side from either conda, homebrew or even default system's. Wdyt?
